DROP TABLE IF EXISTS nau.protocol;
DROP TABLE IF EXISTS nau.winner;
DROP TABLE IF EXISTS nau.dysciplina;
DROP TABLE IF EXISTS nau.kafedra;
DROP TABLE IF EXISTS nau.institute;
DROP TABLE IF EXISTS nau.student;
DROP TABLE IF EXISTS nau.teacher;

CREATE TABLE  nau.dysciplina (
  DYSCIPLINA_ID int(11) NOT NULL,
  NAME varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (DYSCIPLINA_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE  nau.institute (
  INSTITUTE_ID int(11) NOT NULL,
  CODE varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  NAME varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (INSTITUTE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE  nau.kafedra (
  KAFEDRA_ID int(11) NOT NULL,
  NAME varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  INSTITUTE_ID int(11) DEFAULT NULL,
  PRIMARY KEY (KAFEDRA_ID),
  KEY FKF25930BEE64C9595 (INSTITUTE_ID),
  CONSTRAINT FKF25930BEE64C9595 FOREIGN KEY (INSTITUTE_ID) REFERENCES institute (INSTITUTE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE  nau.student (
  STUDENT_ID int(11) NOT NULL AUTO_INCREMENT,
  BIRTH_DATE datetime DEFAULT NULL,
  FIRST_NAME varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  GIVEN_NAME varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  KURS int(11) DEFAULT NULL,
  LAST_NAME varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (STUDENT_ID)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE  nau.teacher (
  ID int(11) NOT NULL AUTO_INCREMENT,
  NAME varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE  nau.winner (
  WINNER_ID int(11) NOT NULL AUTO_INCREMENT,
  POSITION int(11) DEFAULT NULL,
  POSITION_MONU int(11) DEFAULT NULL,
  SCORE int(11) DEFAULT NULL,
  TEACHER varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  INSTITUTE_ID int(11) DEFAULT NULL,
  KAFEDRA_ID int(11) DEFAULT NULL,
  STUDENT_ID int(11) DEFAULT NULL,
  PRIMARY KEY (WINNER_ID),
  KEY FK989EF43FEC049E95 (STUDENT_ID),
  KEY FK989EF43F9D6377B5 (KAFEDRA_ID),
  KEY FK989EF43FE64C9595 (INSTITUTE_ID),
  CONSTRAINT FK989EF43F9D6377B5 FOREIGN KEY (KAFEDRA_ID) REFERENCES kafedra (KAFEDRA_ID),
  CONSTRAINT FK989EF43FE64C9595 FOREIGN KEY (INSTITUTE_ID) REFERENCES institute (INSTITUTE_ID),
  CONSTRAINT FK989EF43FEC049E95 FOREIGN KEY (STUDENT_ID) REFERENCES student (STUDENT_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE  nau.protocol (
  id int(11) NOT NULL AUTO_INCREMENT,
  DATE datetime DEFAULT NULL,
  DYSCIPLINA_NAME varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  NUMBER int(11) DEFAULT NULL,
  DYSCIPLINA_ID int(11) DEFAULT NULL,
  INSTITUTE_ID int(11) DEFAULT NULL,
  KAFEDRA_ID int(11) DEFAULT NULL,
  WINNER_ID int(11) DEFAULT NULL,
  PRIMARY KEY (id),
  KEY FKF3B07E981BA2B73F (WINNER_ID),
  KEY FKF3B07E98DE91179F (DYSCIPLINA_ID),
  KEY FKF3B07E989D6377B5 (KAFEDRA_ID),
  KEY FKF3B07E98E64C9595 (INSTITUTE_ID),
  CONSTRAINT FKF3B07E981BA2B73F FOREIGN KEY (WINNER_ID) REFERENCES winner (WINNER_ID),
  CONSTRAINT FKF3B07E989D6377B5 FOREIGN KEY (KAFEDRA_ID) REFERENCES kafedra (KAFEDRA_ID),
  CONSTRAINT FKF3B07E98DE91179F FOREIGN KEY (DYSCIPLINA_ID) REFERENCES dysciplina (DYSCIPLINA_ID),
  CONSTRAINT FKF3B07E98E64C9595 FOREIGN KEY (INSTITUTE_ID) REFERENCES institute (INSTITUTE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;